version: '3.4'
services:
  # ThingsBoard IoT Gateway Service Configuration
  tb-gateway:
    image: phamchanhuy113/thingsboard-gateway
    container_name: tb-gateway
    restart: always

    # Ports tìm thấy
    ports:
        - "5000:5000"
        - "1052:1052" # BACnet connector
        - "5026:5026" # Modbus TCP connector
        - "50000:50000/tcp" # Socket connector with type TCP
        - "50000:50000/udp" # Socket connector with type UDP

    # Ánh xạ container ra host
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Biến môi trường
    environment:
      - host=cloud.things.vn
      - port=1883
      - accessToken=DEVICE_ACCESS_TOKEN

    # Volumes bind
    volumes:
      - tb-gw-config:/thingsboard_gateway/config
      - tb-gw-logs:/thingsboard_gateway/logs
      - tb-gw-extensions:/thingsboard_gateway/extensions

# Volumes declaration for configurations, extensions and configuration
volumes:
  tb-gw-config:
    name: tb-gw-config
  tb-gw-logs:
    name: tb-gw-logs
  tb-gw-extensions:
    name: tb-gw-extensions
